#ifndef ERROR_H
# define ERROR_H

# include <stdio.h>
# include <stdlib.h>

enum e_error_type
{
	ARGV_ERROR = -22,
	CUB_EXTENSION_ERROR,
	XPM_EXTENSION_ERROR,
	ELEMENT_IDENTIFIER_ERROR,
	EMPTY_PATH,
	MALLOC_ERROR,
	FILE_OPENING_ERROR,
	EMPTY_FILE_ERROR,
	ELEMENT_ARGUMENT_ERROR,
	ELEMENT_TYPE_ERROR,
	DUPLICATE_ELEMENT_ERROR,
	TEXTURE_PATH_ERROR,
	RGB_ARGUMENT_ERROR, // wrong number of arguments
	RGB_EMPTY_VALUE,
	RGB_NAN_ERROR,
	RGB_RANGE_ERROR,
	MAP_EMPTY,
	MAP_EMPTY_LINE,
	MAP_INVALID_CHAR,
	MAP_NO_PLAYER,
	MAP_MULTIPLE_PLAYER,
	MAP_MISSING_WALL
};

void	exit_with_error(int	type);

#endif